workflows:
  android-release:
    name: MAAS PERFUMES Android
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get packages
        script: |
          cd maas_perfumes
          flutter pub get
      - name: Build APK
        script: |
          cd maas_perfumes
          flutter build apk --release
    artifacts:
      - maas_perfumes/build/app/outputs/flutter-apk/app-release.apk
